/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UserInterface;

import javax.swing.ImageIcon;

/**
 *
 * @author rolan
 */
public class MainUI extends javax.swing.JFrame {

    /**
     * Creates new form MainUI
     */
    public MainUI() {
        super("ToonWars");
        initComponents();
        ImageIcon nickImage = new ImageIcon("./../Assets/NickImages/logo-de-avatar-la-leyenda-de-aang-avatar.png");
        this.characterImgNick.setIcon(nickImage);
        ImageIcon cartoonImage = new ImageIcon("./../Assets/CartoonImages/logo-un-show-mas.png");
        this.characterImgCartoon.setIcon(cartoonImage);
        secondQueueNick.setText("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        generalPanel = new javax.swing.JPanel();
        cartoonNetworkPanel = new javax.swing.JPanel();
        cartoonNetworkPanel_title = new javax.swing.JLabel();
        networkPanel_title = new javax.swing.JFormattedTextField();
        jPanel2 = new javax.swing.JPanel();
        chracterSPCartoon = new javax.swing.JLabel();
        chracterAGCartoon_Label = new javax.swing.JLabel();
        chracterMPCartoon_Label = new javax.swing.JLabel();
        characterIDCartoon = new javax.swing.JLabel();
        chracterMPCartoon = new javax.swing.JLabel();
        characterIDCartoon_Label = new javax.swing.JLabel();
        chracterSPCartoon_Label = new javax.swing.JLabel();
        chracterHPCartoon = new javax.swing.JLabel();
        chracterHPCartoon_Label = new javax.swing.JLabel();
        chracterMGCartoon = new javax.swing.JLabel();
        chracterSTCartoon = new javax.swing.JLabel();
        chracterSTCartoon_Label = new javax.swing.JLabel();
        characterImgCartoon = new javax.swing.JLabel();
        chracterAGCartoon = new javax.swing.JLabel();
        chracterMGCartoon_Label = new javax.swing.JLabel();
        secondQueueCartoon_label = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        secondQueueCartoon = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        topQueueCartoon = new javax.swing.JTextArea();
        topQueueCartoon_label = new javax.swing.JLabel();
        supportQueueCartoon_label = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        thirdQueueCartoon = new javax.swing.JTextArea();
        thirdQueueCartoon_label = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        supportQueueCartoon = new javax.swing.JTextArea();
        nickelodeonPanel = new javax.swing.JPanel();
        secondQueueNick_label = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        characterIDNick_Label = new javax.swing.JLabel();
        characterIDNick = new javax.swing.JLabel();
        characterImgNick = new javax.swing.JLabel();
        chracterHPNick_Label = new javax.swing.JLabel();
        chracterHPNick = new javax.swing.JLabel();
        chracterAGNick = new javax.swing.JLabel();
        chracterAGNick_Label = new javax.swing.JLabel();
        chracterSTNick = new javax.swing.JLabel();
        chracterSTNick_Label = new javax.swing.JLabel();
        chracterSPNick = new javax.swing.JLabel();
        chracterSPNick_Label = new javax.swing.JLabel();
        chracterMGNick = new javax.swing.JLabel();
        chracterMGNick_Label = new javax.swing.JLabel();
        chracterMPNick_Label = new javax.swing.JLabel();
        chracterMPNick = new javax.swing.JLabel();
        nickelodeonPanel_title = new javax.swing.JLabel();
        topQueueNick_label = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        secondQueueNick = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        topQueueNick = new javax.swing.JTextArea();
        thirdQueueNick_label = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        thirdQueueNick = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        supportQueueNick = new javax.swing.JTextArea();
        supportQueueNick_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        generalPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cartoonNetworkPanel.setBackground(new java.awt.Color(255, 255, 255));
        cartoonNetworkPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cartoonNetworkPanel_title.setBackground(new java.awt.Color(0, 0, 0));
        cartoonNetworkPanel_title.setFont(new java.awt.Font("Microsoft YaHei", 1, 36)); // NOI18N
        cartoonNetworkPanel_title.setForeground(new java.awt.Color(51, 51, 51));
        cartoonNetworkPanel_title.setText("CARTOON");
        cartoonNetworkPanel.add(cartoonNetworkPanel_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 200, 60));

        networkPanel_title.setBackground(new java.awt.Color(51, 51, 51));
        networkPanel_title.setForeground(new java.awt.Color(255, 255, 255));
        networkPanel_title.setText("NETWORK");
        networkPanel_title.setFocusable(false);
        networkPanel_title.setFont(new java.awt.Font("Microsoft YaHei", 1, 36)); // NOI18N
        cartoonNetworkPanel.add(networkPanel_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 210, 60));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        chracterSPCartoon.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        chracterSPCartoon.setForeground(java.awt.Color.white);
        chracterSPCartoon.setText("0");
        jPanel2.add(chracterSPCartoon, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 54, 23));

        chracterAGCartoon_Label.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        chracterAGCartoon_Label.setForeground(java.awt.Color.white);
        chracterAGCartoon_Label.setText("AG:");
        jPanel2.add(chracterAGCartoon_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 29, -1));

        chracterMPCartoon_Label.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        chracterMPCartoon_Label.setForeground(java.awt.Color.white);
        chracterMPCartoon_Label.setText("MP:");
        jPanel2.add(chracterMPCartoon_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, -1, -1));

        characterIDCartoon.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        characterIDCartoon.setForeground(java.awt.Color.white);
        characterIDCartoon.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jPanel2.add(characterIDCartoon, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 143, 23));

        chracterMPCartoon.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        chracterMPCartoon.setForeground(java.awt.Color.white);
        chracterMPCartoon.setText("0");
        jPanel2.add(chracterMPCartoon, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 54, 23));

        characterIDCartoon_Label.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        characterIDCartoon_Label.setForeground(java.awt.Color.white);
        characterIDCartoon_Label.setText("ID:");
        jPanel2.add(characterIDCartoon_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 41, -1));

        chracterSPCartoon_Label.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        chracterSPCartoon_Label.setForeground(java.awt.Color.white);
        chracterSPCartoon_Label.setText("SP:");
        jPanel2.add(chracterSPCartoon_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 29, -1));

        chracterHPCartoon.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        chracterHPCartoon.setForeground(java.awt.Color.white);
        chracterHPCartoon.setText("0");
        jPanel2.add(chracterHPCartoon, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 54, 23));

        chracterHPCartoon_Label.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        chracterHPCartoon_Label.setForeground(java.awt.Color.white);
        chracterHPCartoon_Label.setText("HP:");
        jPanel2.add(chracterHPCartoon_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 29, -1));

        chracterMGCartoon.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        chracterMGCartoon.setForeground(java.awt.Color.white);
        chracterMGCartoon.setText("0");
        jPanel2.add(chracterMGCartoon, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 54, 23));

        chracterSTCartoon.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        chracterSTCartoon.setForeground(java.awt.Color.white);
        chracterSTCartoon.setText("0");
        jPanel2.add(chracterSTCartoon, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 54, 23));

        chracterSTCartoon_Label.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        chracterSTCartoon_Label.setForeground(java.awt.Color.white);
        chracterSTCartoon_Label.setText("ST:");
        jPanel2.add(chracterSTCartoon_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 29, -1));

        characterImgCartoon.setForeground(java.awt.Color.white);
        characterImgCartoon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/CartoonImages/logo-un-show-mas.png"))); // NOI18N
        characterImgCartoon.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jPanel2.add(characterImgCartoon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 200, 220));

        chracterAGCartoon.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        chracterAGCartoon.setForeground(java.awt.Color.white);
        chracterAGCartoon.setText("0");
        jPanel2.add(chracterAGCartoon, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 54, 23));

        chracterMGCartoon_Label.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        chracterMGCartoon_Label.setForeground(java.awt.Color.white);
        chracterMGCartoon_Label.setText("MG:");
        jPanel2.add(chracterMGCartoon_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 35, -1));

        cartoonNetworkPanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 230, 360));

        secondQueueCartoon_label.setBackground(new java.awt.Color(0, 0, 0));
        secondQueueCartoon_label.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        secondQueueCartoon_label.setForeground(new java.awt.Color(51, 51, 51));
        secondQueueCartoon_label.setText("Second Priority:");
        cartoonNetworkPanel.add(secondQueueCartoon_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 230, 130, 30));

        secondQueueCartoon.setBackground(new java.awt.Color(255, 255, 255));
        secondQueueCartoon.setColumns(20);
        secondQueueCartoon.setRows(5);
        secondQueueCartoon.setBorder(null);
        jScrollPane6.setViewportView(secondQueueCartoon);

        cartoonNetworkPanel.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 260, 80));

        topQueueCartoon.setBackground(new java.awt.Color(255, 255, 255));
        topQueueCartoon.setColumns(20);
        topQueueCartoon.setRows(5);
        topQueueCartoon.setBorder(null);
        jScrollPane5.setViewportView(topQueueCartoon);

        cartoonNetworkPanel.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 260, 80));

        topQueueCartoon_label.setBackground(new java.awt.Color(0, 0, 0));
        topQueueCartoon_label.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        topQueueCartoon_label.setForeground(new java.awt.Color(51, 51, 51));
        topQueueCartoon_label.setText("Top Priority:");
        cartoonNetworkPanel.add(topQueueCartoon_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, 110, 30));

        supportQueueCartoon_label.setBackground(new java.awt.Color(0, 0, 0));
        supportQueueCartoon_label.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        supportQueueCartoon_label.setForeground(new java.awt.Color(51, 51, 51));
        supportQueueCartoon_label.setText("Supports:");
        cartoonNetworkPanel.add(supportQueueCartoon_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 480, 80, 30));

        thirdQueueCartoon.setBackground(new java.awt.Color(255, 255, 255));
        thirdQueueCartoon.setColumns(20);
        thirdQueueCartoon.setRows(5);
        thirdQueueCartoon.setBorder(null);
        jScrollPane7.setViewportView(thirdQueueCartoon);

        cartoonNetworkPanel.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 390, 260, 80));

        thirdQueueCartoon_label.setBackground(new java.awt.Color(0, 0, 0));
        thirdQueueCartoon_label.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        thirdQueueCartoon_label.setForeground(new java.awt.Color(51, 51, 51));
        thirdQueueCartoon_label.setText("Third Priority:");
        cartoonNetworkPanel.add(thirdQueueCartoon_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 360, 110, 30));

        supportQueueCartoon.setBackground(new java.awt.Color(255, 255, 255));
        supportQueueCartoon.setColumns(20);
        supportQueueCartoon.setRows(5);
        supportQueueCartoon.setBorder(null);
        jScrollPane8.setViewportView(supportQueueCartoon);

        cartoonNetworkPanel.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 510, 260, 80));

        generalPanel.add(cartoonNetworkPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, 600, 640));

        nickelodeonPanel.setBackground(new java.awt.Color(255, 153, 0));
        nickelodeonPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        secondQueueNick_label.setBackground(new java.awt.Color(0, 0, 0));
        secondQueueNick_label.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        secondQueueNick_label.setForeground(new java.awt.Color(255, 255, 255));
        secondQueueNick_label.setText("Second Priority:");
        nickelodeonPanel.add(secondQueueNick_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 110, 30));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        characterIDNick_Label.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        characterIDNick_Label.setForeground(new java.awt.Color(255, 153, 0));
        characterIDNick_Label.setText("ID:");

        characterIDNick.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        characterIDNick.setForeground(new java.awt.Color(255, 153, 0));
        characterIDNick.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 1, true));

        characterImgNick.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/NickImages/logo-de-avatar-la-leyenda-de-aang-avatar.png"))); // NOI18N
        characterImgNick.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 1, true));

        chracterHPNick_Label.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        chracterHPNick_Label.setForeground(new java.awt.Color(255, 153, 0));
        chracterHPNick_Label.setText("HP:");

        chracterHPNick.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        chracterHPNick.setForeground(new java.awt.Color(255, 153, 0));
        chracterHPNick.setText("0");

        chracterAGNick.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        chracterAGNick.setForeground(new java.awt.Color(255, 153, 0));
        chracterAGNick.setText("0");

        chracterAGNick_Label.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        chracterAGNick_Label.setForeground(new java.awt.Color(255, 153, 0));
        chracterAGNick_Label.setText("AG:");

        chracterSTNick.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        chracterSTNick.setForeground(new java.awt.Color(255, 153, 0));
        chracterSTNick.setText("0");

        chracterSTNick_Label.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        chracterSTNick_Label.setForeground(new java.awt.Color(255, 153, 0));
        chracterSTNick_Label.setText("ST:");

        chracterSPNick.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        chracterSPNick.setForeground(new java.awt.Color(255, 153, 0));
        chracterSPNick.setText("0");

        chracterSPNick_Label.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        chracterSPNick_Label.setForeground(new java.awt.Color(255, 153, 0));
        chracterSPNick_Label.setText("SP:");

        chracterMGNick.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        chracterMGNick.setForeground(new java.awt.Color(255, 153, 0));
        chracterMGNick.setText("0");

        chracterMGNick_Label.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        chracterMGNick_Label.setForeground(new java.awt.Color(255, 153, 0));
        chracterMGNick_Label.setText("MG:");

        chracterMPNick_Label.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        chracterMPNick_Label.setForeground(new java.awt.Color(255, 153, 0));
        chracterMPNick_Label.setText("MP:");

        chracterMPNick.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        chracterMPNick.setForeground(new java.awt.Color(255, 153, 0));
        chracterMPNick.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(characterImgNick, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(characterIDNick_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(characterIDNick, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(12, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(chracterAGNick_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(chracterAGNick, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(chracterSPNick_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(chracterSPNick, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(chracterHPNick_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(chracterHPNick, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(chracterSTNick_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(chracterSTNick, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(chracterMGNick_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chracterMGNick, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chracterMPNick_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(chracterMPNick, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(characterIDNick, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(characterIDNick_Label))
                .addGap(18, 18, 18)
                .addComponent(characterImgNick, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chracterHPNick, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chracterHPNick_Label)
                    .addComponent(chracterSTNick, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chracterSTNick_Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chracterAGNick, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chracterAGNick_Label)
                    .addComponent(chracterSPNick, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chracterSPNick_Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chracterMGNick, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chracterMGNick_Label)
                    .addComponent(chracterMPNick, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chracterMPNick_Label))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        nickelodeonPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 230, 360));

        nickelodeonPanel_title.setBackground(new java.awt.Color(0, 0, 0));
        nickelodeonPanel_title.setFont(new java.awt.Font("Microsoft YaHei", 1, 36)); // NOI18N
        nickelodeonPanel_title.setForeground(new java.awt.Color(255, 255, 255));
        nickelodeonPanel_title.setText("NICKELODEON");
        nickelodeonPanel.add(nickelodeonPanel_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 280, 60));

        topQueueNick_label.setBackground(new java.awt.Color(0, 0, 0));
        topQueueNick_label.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        topQueueNick_label.setForeground(new java.awt.Color(255, 255, 255));
        topQueueNick_label.setText("Top Priority:");
        nickelodeonPanel.add(topQueueNick_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 110, 30));

        secondQueueNick.setBackground(new java.awt.Color(255, 255, 255));
        secondQueueNick.setColumns(20);
        secondQueueNick.setRows(5);
        secondQueueNick.setBorder(null);
        jScrollPane1.setViewportView(secondQueueNick);

        nickelodeonPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 260, 80));

        topQueueNick.setBackground(new java.awt.Color(255, 255, 255));
        topQueueNick.setColumns(20);
        topQueueNick.setRows(5);
        topQueueNick.setBorder(null);
        jScrollPane2.setViewportView(topQueueNick);

        nickelodeonPanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 260, 80));

        thirdQueueNick_label.setBackground(new java.awt.Color(0, 0, 0));
        thirdQueueNick_label.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        thirdQueueNick_label.setForeground(new java.awt.Color(255, 255, 255));
        thirdQueueNick_label.setText("Third Priority:");
        nickelodeonPanel.add(thirdQueueNick_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 110, 30));

        thirdQueueNick.setBackground(new java.awt.Color(255, 255, 255));
        thirdQueueNick.setColumns(20);
        thirdQueueNick.setRows(5);
        thirdQueueNick.setBorder(null);
        jScrollPane3.setViewportView(thirdQueueNick);

        nickelodeonPanel.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 260, 80));

        supportQueueNick.setBackground(new java.awt.Color(255, 255, 255));
        supportQueueNick.setColumns(20);
        supportQueueNick.setRows(5);
        supportQueueNick.setBorder(null);
        jScrollPane4.setViewportView(supportQueueNick);

        nickelodeonPanel.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, 260, 80));

        supportQueueNick_label.setBackground(new java.awt.Color(0, 0, 0));
        supportQueueNick_label.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        supportQueueNick_label.setForeground(new java.awt.Color(255, 255, 255));
        supportQueueNick_label.setText("Supports:");
        nickelodeonPanel.add(supportQueueNick_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 110, 30));

        generalPanel.add(nickelodeonPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 640));

        getContentPane().add(generalPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cartoonNetworkPanel;
    private javax.swing.JLabel cartoonNetworkPanel_title;
    private javax.swing.JLabel characterIDCartoon;
    private javax.swing.JLabel characterIDCartoon_Label;
    private javax.swing.JLabel characterIDNick;
    private javax.swing.JLabel characterIDNick_Label;
    private javax.swing.JLabel characterImgCartoon;
    private javax.swing.JLabel characterImgNick;
    private javax.swing.JLabel chracterAGCartoon;
    private javax.swing.JLabel chracterAGCartoon_Label;
    private javax.swing.JLabel chracterAGNick;
    private javax.swing.JLabel chracterAGNick_Label;
    private javax.swing.JLabel chracterHPCartoon;
    private javax.swing.JLabel chracterHPCartoon_Label;
    private javax.swing.JLabel chracterHPNick;
    private javax.swing.JLabel chracterHPNick_Label;
    private javax.swing.JLabel chracterMGCartoon;
    private javax.swing.JLabel chracterMGCartoon_Label;
    private javax.swing.JLabel chracterMGNick;
    private javax.swing.JLabel chracterMGNick_Label;
    private javax.swing.JLabel chracterMPCartoon;
    private javax.swing.JLabel chracterMPCartoon_Label;
    private javax.swing.JLabel chracterMPNick;
    private javax.swing.JLabel chracterMPNick_Label;
    private javax.swing.JLabel chracterSPCartoon;
    private javax.swing.JLabel chracterSPCartoon_Label;
    private javax.swing.JLabel chracterSPNick;
    private javax.swing.JLabel chracterSPNick_Label;
    private javax.swing.JLabel chracterSTCartoon;
    private javax.swing.JLabel chracterSTCartoon_Label;
    private javax.swing.JLabel chracterSTNick;
    private javax.swing.JLabel chracterSTNick_Label;
    private javax.swing.JPanel generalPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JFormattedTextField networkPanel_title;
    private javax.swing.JPanel nickelodeonPanel;
    private javax.swing.JLabel nickelodeonPanel_title;
    private javax.swing.JTextArea secondQueueCartoon;
    private javax.swing.JLabel secondQueueCartoon_label;
    private javax.swing.JTextArea secondQueueNick;
    private javax.swing.JLabel secondQueueNick_label;
    private javax.swing.JTextArea supportQueueCartoon;
    private javax.swing.JLabel supportQueueCartoon_label;
    private javax.swing.JTextArea supportQueueNick;
    private javax.swing.JLabel supportQueueNick_label;
    private javax.swing.JTextArea thirdQueueCartoon;
    private javax.swing.JLabel thirdQueueCartoon_label;
    private javax.swing.JTextArea thirdQueueNick;
    private javax.swing.JLabel thirdQueueNick_label;
    private javax.swing.JTextArea topQueueCartoon;
    private javax.swing.JLabel topQueueCartoon_label;
    private javax.swing.JTextArea topQueueNick;
    private javax.swing.JLabel topQueueNick_label;
    // End of variables declaration//GEN-END:variables
}
